%%{ init: { 'theme': 'dark', 'flowchart': { 'curve': 'basis' } } }%%
graph LR

  subgraph Module: `src
    on_button_pressed_event__Button_Pressed_____None["on_button_pressed(event: Button.Pressed) -> None"]
    update_time_range_seconds_____None["update_time_range(seconds) -> None"]
  end

  subgraph Module: src
  end

  subgraph root
  end

  subgraph src
  end


